//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fırst_WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public long Department_Id { get; set; }
        public string Department_IdName { get; set; }
        public string Description { get; set; }
        public string Phot { get; set; }
    }
}
