//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fırst_WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long Student_Id { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string Gender { get; set; }
        public string BirthDay { get; set; }
        public string Modil { get; set; }
        public Nullable<long> Department_Id { get; set; }
    }
}
